// Types for Souqah application

export interface Subcategory {
    id: string;
    name: string;
    slug: string;
    count: number;
    icon?: string;
}

export interface Category {
    id: string;
    name: string;
    slug: string;
    icon: string;
    count: number;
    color: string;
    subcategories?: Subcategory[];
}

export interface Ad {
    id: string;
    title: string;
    description: string;
    price: number;
    location: string;
    city: string;
    date: string;
    image: string;
    images: string[];
    category: string;
    categorySlug: string;
    subcategory?: string;
    subcategorySlug?: string;
    featured: boolean;
    userId: string;
    userName: string;
    userPhone: string;
    views: number;
}

export interface User {
    id: string;
    name: string;
    email: string;
    phone: string;
    avatar: string;
    joinDate: string;
    adsCount: number;
    rating: number;
    verified: boolean;
    phoneVerified: boolean;
    badges: ("verified" | "business" | "trusted" | "premium")[];
}

// Expanded categories with subcategories and icons
export const categories: Category[] = [
    {
        id: "1",
        name: "سيارات",
        slug: "cars",
        icon: "🚗",
        count: 25420,
        color: "#ef4444",
        subcategories: [
            { id: "1-1", name: "تويوتا", slug: "toyota", count: 4500, icon: "🚙" },
            { id: "1-2", name: "لكزس", slug: "lexus", count: 2100, icon: "🏎️" },
            { id: "1-3", name: "نيسان", slug: "nissan", count: 3200, icon: "🚘" },
            { id: "1-4", name: "هيونداي", slug: "hyundai", count: 2800, icon: "🚐" },
            { id: "1-5", name: "كيا", slug: "kia", count: 1900, icon: "🚕" },
            { id: "1-6", name: "شيفروليه", slug: "chevrolet", count: 1500, icon: "🛻" },
            { id: "1-7", name: "فورد", slug: "ford", count: 1200, icon: "🚓" },
            { id: "1-8", name: "مرسيدس", slug: "mercedes", count: 2500, icon: "🚔" },
            { id: "1-9", name: "بي ام دبليو", slug: "bmw", count: 1800, icon: "🏁" },
            { id: "1-10", name: "جيب", slug: "jeep", count: 1400, icon: "🚙" },
            { id: "1-11", name: "قطع غيار", slug: "parts", count: 1520, icon: "🔧" },
            { id: "1-12", name: "دراجات نارية", slug: "motorcycles", count: 980, icon: "🏍️" },
        ],
    },
    {
        id: "2",
        name: "عقارات",
        slug: "realestate",
        icon: "🏠",
        count: 18750,
        color: "#22c55e",
        subcategories: [
            { id: "2-1", name: "شقق للإيجار", slug: "apartments-rent", count: 5200, icon: "🏢" },
            { id: "2-2", name: "شقق للبيع", slug: "apartments-sale", count: 3100, icon: "🏬" },
            { id: "2-3", name: "فلل للإيجار", slug: "villas-rent", count: 1800, icon: "🏡" },
            { id: "2-4", name: "فلل للبيع", slug: "villas-sale", count: 2400, icon: "🏘️" },
            { id: "2-5", name: "أراضي", slug: "lands", count: 2500, icon: "🌍" },
            { id: "2-6", name: "عمارات", slug: "buildings", count: 950, icon: "🏗️" },
            { id: "2-7", name: "محلات تجارية", slug: "shops", count: 1200, icon: "🏪" },
            { id: "2-8", name: "مكاتب", slug: "offices", count: 800, icon: "🏛️" },
            { id: "2-9", name: "استراحات", slug: "resorts", count: 600, icon: "🏖️" },
            { id: "2-10", name: "مزارع", slug: "farms", count: 200, icon: "🌾" },
        ],
    },
    {
        id: "3",
        name: "الكترونيات",
        slug: "electronics",
        icon: "📱",
        count: 22300,
        color: "#3b82f6",
        subcategories: [
            { id: "3-1", name: "جوالات", slug: "phones", count: 8500, icon: "📲" },
            { id: "3-2", name: "لابتوب", slug: "laptops", count: 3200, icon: "💻" },
            { id: "3-3", name: "تابلت", slug: "tablets", count: 1800, icon: "📟" },
            { id: "3-4", name: "شاشات وتلفزيونات", slug: "tvs", count: 2100, icon: "📺" },
            { id: "3-5", name: "ألعاب فيديو", slug: "gaming", count: 2500, icon: "🎮" },
            { id: "3-6", name: "كاميرات", slug: "cameras", count: 980, icon: "📷" },
            { id: "3-7", name: "سماعات", slug: "audio", count: 1500, icon: "🎧" },
            { id: "3-8", name: "طابعات", slug: "printers", count: 420, icon: "🖨️" },
            { id: "3-9", name: "اكسسوارات", slug: "accessories", count: 1300, icon: "🔌" },
        ],
    },
    {
        id: "4",
        name: "أثاث ومفروشات",
        slug: "furniture",
        icon: "🛋️",
        count: 9520,
        color: "#f59e0b",
        subcategories: [
            { id: "4-1", name: "غرف نوم", slug: "bedrooms", count: 2200, icon: "🛏️" },
            { id: "4-2", name: "غرف جلوس", slug: "living-rooms", count: 1800, icon: "🛋️" },
            { id: "4-3", name: "مطابخ", slug: "kitchens", count: 1200, icon: "🍳" },
            { id: "4-4", name: "مكاتب منزلية", slug: "home-office", count: 650, icon: "🪑" },
            { id: "4-5", name: "سجاد وموكيت", slug: "carpets", count: 890, icon: "🧶" },
            { id: "4-6", name: "ستائر", slug: "curtains", count: 560, icon: "🪟" },
            { id: "4-7", name: "أجهزة منزلية", slug: "appliances", count: 1420, icon: "🧊" },
            { id: "4-8", name: "ديكور", slug: "decor", count: 780, icon: "🖼️" },
        ],
    },
    {
        id: "5",
        name: "أزياء وموضة",
        slug: "fashion",
        icon: "👔",
        count: 12890,
        color: "#ec4899",
        subcategories: [
            { id: "5-1", name: "ملابس رجالية", slug: "men-clothes", count: 3500, icon: "👕" },
            { id: "5-2", name: "ملابس نسائية", slug: "women-clothes", count: 4200, icon: "👗" },
            { id: "5-3", name: "ملابس أطفال", slug: "kids-clothes", count: 1800, icon: "🧒" },
            { id: "5-4", name: "أحذية", slug: "shoes", count: 1500, icon: "👟" },
            { id: "5-5", name: "حقائب", slug: "bags", count: 890, icon: "👜" },
            { id: "5-6", name: "ساعات", slug: "watches", count: 650, icon: "⌚" },
            { id: "5-7", name: "مجوهرات", slug: "jewelry", count: 350, icon: "💍" },
        ],
    },
    {
        id: "6",
        name: "وظائف",
        slug: "jobs",
        icon: "💼",
        count: 8200,
        color: "#8b5cf6",
        subcategories: [
            { id: "6-1", name: "تقنية المعلومات", slug: "it", count: 1800, icon: "💻" },
            { id: "6-2", name: "هندسة", slug: "engineering", count: 1200, icon: "⚙️" },
            { id: "6-3", name: "تسويق ومبيعات", slug: "marketing", count: 1500, icon: "📈" },
            { id: "6-4", name: "محاسبة ومالية", slug: "accounting", count: 980, icon: "🧮" },
            { id: "6-5", name: "إدارة", slug: "management", count: 650, icon: "👨‍💼" },
            { id: "6-6", name: "طبي وصحي", slug: "medical", count: 750, icon: "🏥" },
            { id: "6-7", name: "تعليم", slug: "education", count: 520, icon: "🎓" },
            { id: "6-8", name: "عمل حر", slug: "freelance", count: 800, icon: "🏠" },
        ],
    },
    {
        id: "7",
        name: "خدمات",
        slug: "services",
        icon: "🔧",
        count: 11600,
        color: "#06b6d4",
        subcategories: [
            { id: "7-1", name: "صيانة وإصلاح", slug: "maintenance", count: 2200, icon: "🛠️" },
            { id: "7-2", name: "نقل وشحن", slug: "shipping", count: 1800, icon: "🚚" },
            { id: "7-3", name: "تنظيف", slug: "cleaning", count: 1500, icon: "🧹" },
            { id: "7-4", name: "تصميم وبرمجة", slug: "design", count: 1200, icon: "🎨" },
            { id: "7-5", name: "دروس خصوصية", slug: "tutoring", count: 980, icon: "📖" },
            { id: "7-6", name: "تصوير", slug: "photography", count: 650, icon: "📸" },
            { id: "7-7", name: "رحلات وسياحة", slug: "travel", count: 1100, icon: "✈️" },
            { id: "7-8", name: "مناسبات وحفلات", slug: "events", count: 870, icon: "🎉" },
            { id: "7-9", name: "رعاية صحية", slug: "healthcare", count: 500, icon: "💊" },
        ],
    },
    {
        id: "8",
        name: "حيوانات",
        slug: "animals",
        icon: "🐾",
        count: 5400,
        color: "#84cc16",
        subcategories: [
            { id: "8-1", name: "قطط", slug: "cats", count: 1800, icon: "🐱" },
            { id: "8-2", name: "كلاب", slug: "dogs", count: 1200, icon: "🐕" },
            { id: "8-3", name: "طيور", slug: "birds", count: 950, icon: "🦜" },
            { id: "8-4", name: "خيول", slug: "horses", count: 420, icon: "🐴" },
            { id: "8-5", name: "أسماك زينة", slug: "fish", count: 380, icon: "🐠" },
            { id: "8-6", name: "مستلزمات حيوانات", slug: "pet-supplies", count: 650, icon: "🦴" },
        ],
    },
    {
        id: "9",
        name: "رياضة",
        slug: "sports",
        icon: "⚽",
        count: 4800,
        color: "#f97316",
        subcategories: [
            { id: "9-1", name: "أجهزة رياضية", slug: "gym-equipment", count: 1200, icon: "🏋️" },
            { id: "9-2", name: "دراجات هوائية", slug: "bicycles", count: 850, icon: "🚴" },
            { id: "9-3", name: "ملابس رياضية", slug: "sportswear", count: 980, icon: "👟" },
            { id: "9-4", name: "مستلزمات كرة قدم", slug: "football", count: 650, icon: "⚽" },
            { id: "9-5", name: "سباحة وغوص", slug: "swimming", count: 420, icon: "🏊" },
            { id: "9-6", name: "تخييم ورحلات", slug: "camping", count: 700, icon: "⛺" },
        ],
    },
    {
        id: "10",
        name: "كتب وتعليم",
        slug: "books",
        icon: "📚",
        count: 3200,
        color: "#0ea5e9",
        subcategories: [
            { id: "10-1", name: "كتب دراسية", slug: "textbooks", count: 1100, icon: "📖" },
            { id: "10-2", name: "روايات وقصص", slug: "novels", count: 650, icon: "📕" },
            { id: "10-3", name: "كتب دينية", slug: "religious", count: 450, icon: "📗" },
            { id: "10-4", name: "كتب أطفال", slug: "children-books", count: 380, icon: "📘" },
            { id: "10-5", name: "قرطاسية", slug: "stationery", count: 420, icon: "✏️" },
            { id: "10-6", name: "دورات تدريبية", slug: "courses", count: 200, icon: "🎓" },
        ],
    },
    {
        id: "11",
        name: "طعام ومشروبات",
        slug: "food",
        icon: "🍽️",
        count: 2800,
        color: "#dc2626",
        subcategories: [
            { id: "11-1", name: "وجبات منزلية", slug: "homemade", count: 980, icon: "🍲" },
            { id: "11-2", name: "حلويات", slug: "sweets", count: 650, icon: "🍰" },
            { id: "11-3", name: "قهوة وشاي", slug: "coffee", count: 420, icon: "☕" },
            { id: "11-4", name: "تمور", slug: "dates", count: 350, icon: "🌴" },
            { id: "11-5", name: "عسل", slug: "honey", count: 250, icon: "🍯" },
            { id: "11-6", name: "معدات مطبخ", slug: "kitchen-equipment", count: 150, icon: "🍳" },
        ],
    },
    {
        id: "12",
        name: "أخرى",
        slug: "other",
        icon: "📦",
        count: 9800,
        color: "#6b7280",
        subcategories: [
            { id: "12-1", name: "مستلزمات أطفال", slug: "baby-items", count: 2100, icon: "👶" },
            { id: "12-2", name: "مستلزمات طبية", slug: "medical-supplies", count: 980, icon: "💉" },
            { id: "12-3", name: "عطور ومكياج", slug: "perfumes", count: 1500, icon: "💄" },
            { id: "12-4", name: "هدايا", slug: "gifts", count: 650, icon: "🎁" },
            { id: "12-5", name: "تحف وأنتيك", slug: "antiques", count: 420, icon: "🏺" },
            { id: "12-6", name: "متفرقات", slug: "misc", count: 4150, icon: "📦" },
        ],
    },
];

// Sample ads
export const sampleAds: Ad[] = [
    {
        id: "1",
        title: "كامري 2023 فل كامل - ممشى قليل",
        description: "سيارة تويوتا كامري موديل 2023 فل كامل، ممشى 25 ألف كم فقط، لون أبيض لؤلؤي، جميع الفحوصات متوفرة",
        price: 125000,
        location: "الرياض",
        city: "الرياض",
        date: "منذ ساعة",
        image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
        images: [],
        category: "سيارات",
        categorySlug: "cars",
        subcategory: "تويوتا",
        subcategorySlug: "toyota",
        featured: true,
        userId: "u1",
        userName: "أحمد محمد",
        userPhone: "0500000000",
        views: 234,
    },
    {
        id: "2",
        title: "شقة للإيجار - حي النرجس",
        description: "شقة 3 غرف وصالة ومطبخ و2 حمام، مدخل خاص، موقع مميز قريب من الخدمات",
        price: 35000,
        location: "الرياض - حي النرجس",
        city: "الرياض",
        date: "منذ 3 ساعات",
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
        images: [],
        category: "عقارات",
        categorySlug: "realestate",
        subcategory: "شقق للإيجار",
        subcategorySlug: "apartments-rent",
        featured: true,
        userId: "u2",
        userName: "عقارات الخليج",
        userPhone: "0500000001",
        views: 567,
    },
    {
        id: "3",
        title: "ايفون 15 برو ماكس 256GB",
        description: "ايفون 15 برو ماكس جديد بكرتونه، ضمان سنة، لون تيتانيوم أزرق",
        price: 4800,
        location: "جدة",
        city: "جدة",
        date: "منذ 5 ساعات",
        image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800",
        images: [],
        category: "الكترونيات",
        categorySlug: "electronics",
        subcategory: "جوالات",
        subcategorySlug: "phones",
        featured: false,
        userId: "u3",
        userName: "متجر التقنية",
        userPhone: "0500000002",
        views: 189,
    },
    {
        id: "4",
        title: "طقم كنب مودرن جديد",
        description: "طقم كنب 7 مقاعد تصميم مودرن، قماش تركي فاخر، ضمان 5 سنوات",
        price: 8500,
        location: "الدمام",
        city: "الدمام",
        date: "منذ يوم",
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        images: [],
        category: "أثاث ومفروشات",
        categorySlug: "furniture",
        subcategory: "غرف جلوس",
        subcategorySlug: "living-rooms",
        featured: false,
        userId: "u4",
        userName: "أثاث المنزل",
        userPhone: "0500000003",
        views: 98,
    },
    {
        id: "5",
        title: "لاند كروزر 2022 VXR",
        description: "لاند كروزر VXR فل كامل، ممشى 40 ألف، نظيف جداً، وكالة",
        price: 320000,
        location: "الرياض",
        city: "الرياض",
        date: "منذ يومين",
        image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800",
        images: [],
        category: "سيارات",
        categorySlug: "cars",
        subcategory: "تويوتا",
        subcategorySlug: "toyota",
        featured: true,
        userId: "u5",
        userName: "معرض السيارات",
        userPhone: "0500000004",
        views: 445,
    },
    {
        id: "6",
        title: "فيلا دوبلكس للبيع - شمال الرياض",
        description: "فيلا دوبلكس 400م، 6 غرف، حديقة خاصة، مسبح، موقع استراتيجي",
        price: 2500000,
        location: "الرياض - حي الملقا",
        city: "الرياض",
        date: "منذ 3 أيام",
        image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800",
        images: [],
        category: "عقارات",
        categorySlug: "realestate",
        subcategory: "فلل للبيع",
        subcategorySlug: "villas-sale",
        featured: false,
        userId: "u6",
        userName: "مكتب الفخامة العقاري",
        userPhone: "0500000005",
        views: 789,
    },
    {
        id: "7",
        title: "ماك بوك برو M3 Pro",
        description: "ماك بوك برو 14 انش، شريحة M3 Pro، 18GB رام، 512GB SSD، جديد",
        price: 9500,
        location: "مكة",
        city: "مكة",
        date: "منذ 4 أيام",
        image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
        images: [],
        category: "الكترونيات",
        categorySlug: "electronics",
        subcategory: "لابتوب",
        subcategorySlug: "laptops",
        featured: false,
        userId: "u7",
        userName: "تقنيات المستقبل",
        userPhone: "0500000006",
        views: 156,
    },
    {
        id: "8",
        title: "مطلوب مهندس برمجيات",
        description: "نبحث عن مهندس برمجيات خبرة 3 سنوات في React و Node.js، راتب مجزي",
        price: 25000,
        location: "الرياض",
        city: "الرياض",
        date: "منذ أسبوع",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
        images: [],
        category: "وظائف",
        categorySlug: "jobs",
        subcategory: "تقنية المعلومات",
        subcategorySlug: "it",
        featured: false,
        userId: "u8",
        userName: "شركة التقنية",
        userPhone: "0500000007",
        views: 320,
    },
    {
        id: "9",
        title: "قط شيرازي للبيع",
        description: "قط شيرازي أصلي، عمره 3 شهور، ذكر، محصن ومعه جواز سفر",
        price: 1500,
        location: "جدة",
        city: "جدة",
        date: "منذ ساعتين",
        image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800",
        images: [],
        category: "حيوانات",
        categorySlug: "animals",
        subcategory: "قطط",
        subcategorySlug: "cats",
        featured: false,
        userId: "u9",
        userName: "متجر الحيوانات",
        userPhone: "0500000008",
        views: 145,
    },
    {
        id: "10",
        title: "دراجة هوائية رياضية",
        description: "دراجة هوائية ماركة Trek، موديل 2023، مستخدمة استخدام خفيف",
        price: 2200,
        location: "الرياض",
        city: "الرياض",
        date: "منذ 6 ساعات",
        image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800",
        images: [],
        category: "رياضة",
        categorySlug: "sports",
        subcategory: "دراجات هوائية",
        subcategorySlug: "bicycles",
        featured: false,
        userId: "u10",
        userName: "سعد الرياضي",
        userPhone: "0500000009",
        views: 78,
    },
];

// Cities
export const saudiCities = [
    "الرياض",
    "جدة",
    "مكة",
    "المدينة",
    "الدمام",
    "الخبر",
    "الطائف",
    "تبوك",
    "أبها",
    "القصيم",
    "حائل",
    "نجران",
    "الجوف",
    "الباحة",
    "الجبيل",
    "ينبع",
    "الأحساء",
    "خميس مشيط",
];

// Neighborhoods/Districts per city
export const cityNeighborhoods: Record<string, string[]> = {
    "الرياض": [
        "النرجس",
        "الملقا",
        "العليا",
        "الورود",
        "الربوة",
        "الملك فهد",
        "السلي",
        "اليرموك",
        "الروضة",
        "النخيل",
        "الياسمين",
        "الصحافة",
        "النسيم",
        "الشفا",
        "العزيزية",
        "المروج",
        "الرمال",
        "المعذر",
        "الحمراء",
        "السويدي",
        "الدار البيضاء",
        "حطين",
        "الغدير",
        "العارض",
        "القيروان",
        "الندى",
        "المهدية",
        "الفيحاء",
        "المرسلات",
        "أم الحمام",
    ],
    "جدة": [
        "الحمراء",
        "الروضة",
        "الزهراء",
        "السلامة",
        "الشرفية",
        "النزهة",
        "المروة",
        "الفيصلية",
        "البوادي",
        "الصفا",
        "الربوة",
        "المحمدية",
        "أبحر الشمالية",
        "أبحر الجنوبية",
        "الشاطئ",
        "الخالدية",
        "النعيم",
        "الفيحاء",
        "البساتين",
        "الريان",
        "الوزيرية",
        "المرجان",
        "الأمير فواز",
        "السنابل",
        "الحمدانية",
    ],
    "مكة": [
        "العزيزية",
        "الشوقية",
        "الزاهر",
        "العوالي",
        "الحمراء",
        "الرصيفة",
        "الشرائع",
        "النسيم",
        "بطحاء قريش",
        "الكعكية",
        "العمرة",
        "الهجرة",
        "المسفلة",
        "جرهم",
        "الشهداء",
    ],
    "المدينة": [
        "العزيزية",
        "السلام",
        "الشفاء",
        "قباء",
        "العوالي",
        "الحرة الشرقية",
        "الحرة الغربية",
        "بني ظفر",
        "المناخة",
        "السيح",
        "الأزهري",
        "النخيل",
        "الدفاع",
        "الملك فهد",
    ],
    "الدمام": [
        "الفيصلية",
        "الشاطئ",
        "الجلوية",
        "المريكبات",
        "الروضة",
        "العزيزية",
        "السوق",
        "القادسية",
        "الفردوس",
        "الضباب",
        "النخيل",
        "الريان",
        "بدر",
        "أحد",
        "المزروعية",
    ],
    "الخبر": [
        "الجوهرة",
        "الراكة الجنوبية",
        "الراكة الشمالية",
        "العقربية",
        "الخبر الشمالية",
        "الخبر الجنوبية",
        "التحلية",
        "اليرموك",
        "الحزام الذهبي",
        "الصواري",
        "البحيرات",
        "العزيزية",
        "الكورنيش",
        "العليا",
    ],
    "الطائف": [
        "الحلقة الغربية",
        "الحلقة الشرقية",
        "الهدا",
        "الشفا",
        "الفيصلية",
        "النسيم",
        "الريان",
        "السلامة",
        "العزيزية",
        "القطبية",
        "حوايا",
        "الوهط",
    ],
    "تبوك": [
        "السليمانية",
        "المروج",
        "الفيصلية",
        "المصيف",
        "العزيزية",
        "الورود",
        "الروضة",
        "القادسية",
        "المنشية",
        "النهضة",
    ],
    "أبها": [
        "المنسك",
        "المفتاحة",
        "الخالدية",
        "البديع",
        "ذرة",
        "الموظفين",
        "الورود",
        "الحزام الأخضر",
        "النميص",
        "شمسان",
    ],
    "القصيم": [
        "الصفراء",
        "الخليج",
        "الربوة",
        "المنار",
        "الراشد",
        "الفاخرية",
        "السلام",
        "الطرفية",
        "النقع",
        "الوزارات",
    ],
    "حائل": [
        "العزيزية",
        "المصيف",
        "الخزامى",
        "النقرة",
        "المحطة",
        "الشفاء",
        "السمراء",
        "الورود",
        "صبابة",
    ],
    "نجران": [
        "الفيصلية",
        "شرق الإمارة",
        "غرب الإمارة",
        "المنطقة الصناعية",
        "الشرفة",
        "الموفجة",
        "المخيم",
        "أبو السعود",
    ],
    "الجوف": [
        "الصديق",
        "الفيصلية",
        "السويس",
        "النهضة",
        "العزيزية",
        "الورود",
        "المطار",
        "قارا",
    ],
    "الباحة": [
        "الخالدية",
        "السلامة",
        "الصدر",
        "الملك فهد",
        "النزهة",
        "السوق",
        "الحزام",
        "الرميعة",
    ],
    "الجبيل": [
        "الفناتير",
        "الحويلات",
        "الدانة",
        "الدفي",
        "الجوهرة",
        "المرجان",
        "الفاروق",
        "القدس",
    ],
    "ينبع": [
        "الشاطئ",
        "الحدائق",
        "السوق",
        "البحر",
        "العزيزية",
        "الرضا",
        "الصناعية",
        "الميناء",
    ],
    "الأحساء": [
        "الهفوف",
        "المبرز",
        "العيون",
        "الجفر",
        "العمران",
        "الطرف",
        "القارة",
        "الشقيق",
    ],
    "خميس مشيط": [
        "الهجرة",
        "الحزام الأخضر",
        "الضباب",
        "المنتزه",
        "الربوة",
        "السد",
        "السلام",
        "النهضة",
    ],
};

// Get neighborhoods for a specific city
export const getNeighborhoods = (city: string): string[] => {
    return cityNeighborhoods[city] || [];
};

// Utility functions
export const formatPrice = (price: number): string => {
    return new Intl.NumberFormat("ar-SA", {
        style: "currency",
        currency: "SAR",
        minimumFractionDigits: 0,
    }).format(price);
};

export const formatNumber = (num: number): string => {
    return new Intl.NumberFormat("ar-SA").format(num);
};

// Helper to get category by slug
export const getCategoryBySlug = (slug: string): Category | undefined => {
    return categories.find((c) => c.slug === slug);
};

// Helper to get subcategory by slug
export const getSubcategoryBySlug = (categorySlug: string, subcategorySlug: string): Subcategory | undefined => {
    const category = getCategoryBySlug(categorySlug);
    return category?.subcategories?.find((s) => s.slug === subcategorySlug);
};
